<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>Eirene</RootNamespace>
	  <UserSecretsId>5601635f-8108-415a-8b30-84f7b2c2d6dc</UserSecretsId>
  </PropertyGroup>

	<ItemGroup>
	  <Compile Remove="images\**" />
	  <Content Remove="images\**" />
	  <EmbeddedResource Remove="images\**" />
	  <None Remove="images\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CloudinaryDotNet" Version="1.28.0" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="9.0.0" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.0" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.9" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		  <PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="pythonnet" Version="3.0.5" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Eirene.BLL\Eirene.BLL.csproj" />
		<ProjectReference Include="..\EireneMVC\EireneMVC.csproj" />
	</ItemGroup>

</Project>
